apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: external-cluster-secret-store
spec:
  provider:
    gcpsm:
      projectID: irori-gcloud
      auth:
        workloadIdentity:
          clusterLocation: us-west1-a
          clusterName: irori-dev
          serviceAccountRef:
            name: external-secrets-wl-sa
            namespace: external-secrets
