apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-external-secret
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-cluster-secret-store
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-api-token
      remoteRef:
        key: cloudflare-api-token
        version: latest
