apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-external-secret
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-cluster-secret-store
  target:
    name: datadog-secret
    creationPolicy: Owner
  data:
    - secretKey: datadog-secret
      remoteRef:
        key: datadog-secret
        version: latest

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-external-secret
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-cluster-secret-store
  target:
    name: datadog-values
    creationPolicy: Owner
  data:
    - secretKey: datadog-values
      remoteRef:
        key: datadog-values
        version: lates
