apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kmnz-mysql-external-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-cluster-secret-store
  target:
    name: kmnz-mysql-password
    creationPolicy: Owner
  data:
    - secretKey: kmnz-mysql-password
      remoteRef:
        key: kmnz-mysql-password
        version: latest
