apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - path: cashly
          - path: kmnz
          - path: nginx
          - path: portfolio
          - path: sandbox

  template:
    metadata:
      name: "{{ path }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/Irori235/manifest.git
        targetRevision: main
        path: "{{ path }}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{ path }}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
